# Generated by Django 5.2.8 on 2025-11-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='productos.etiqueta'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
